# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sanford.lshn
PackageVersion: 0.3.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lshn.exe
  PortableCommandAlias: lshn
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sanford/lshn/releases/download/v0.3.1/lshn-windows-x64.zip
  InstallerSha256: 17FD0FD205918C47227C6208BE1DB720A4C061B8283894D88EAF0BBCBD08730C
ManifestType: installer
ManifestVersion: 1.12.0
