# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sanford.lsnet
PackageVersion: 0.6.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lsnet.exe
  PortableCommandAlias: lsnet
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sanford/lsnet/releases/download/v0.6.1/lsnet-windows-x64.zip
  InstallerSha256: 97A84E902F3B94F3EA6510FEB29505B41B010636B6A7290CDBE700ACDA30662B
ManifestType: installer
ManifestVersion: 1.12.0
